spring:
  application:
    name: myScaffold
  aop:
    auto: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_library?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatabookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 172.16.1.238
    database: 9
    password: ''
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  rabbitmq:
    host: 172.16.1.238
    port: 5672
    username: xydata
    password: xydata

mybatis:
  configuration:
    jdbc-type-for-null: 'NULL'
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8089

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    com.shujuan: debug
  config: classpath:logback.xml
